In [1]:
from bs4 import BeautifulSoup as soup
import requests
import pandas as pd
import time
import random
import re
from datetime import date
import os
import glob
import regex as re
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras import callbacks
from keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from matplotlib import pyplot
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow import keras
import tensorflow as tf
physical_devices = tf.config.list_physical_devices('GPU') 
for device in physical_devices:
    tf.config.experimental.set_memory_growth(device, True)
import pickle

In [10]:
sc_X = pickle.load(open('sc_X3.pkl','rb'))
sc_Y = pickle.load(open('sc_Y3.pkl','rb'))
model = keras.models.load_model('C://Users/Akash/New folder (4)/Untitled Folder/model3')
model.load_weights('weights_realfeel3.h5')
path = 'C://Users/Akash/New folder (4)/Untitled Folder/north/'
all_filenames = []
cities = ["bangalore", "chennai", "hyderabad", "thiruvananthapuram"]
for city in cities:
#     data_files = 'C://Users/Akash/New folder (4)/Untitled Folder/north/*2021.csv'
# all_filenames = [i for i in glob.glob(f"*{file_extension}")]
    all_filenames.append(path+city+'-2018.csv')
for file in all_filenames:
    df = pd.read_csv(file)
    df['newyear'] = pd.to_datetime('2018/01/01')
    df['date']=pd.to_datetime(df['date'])
    df['days']=df['date'] - df['newyear']
    df['days'] = df['days'].dt.days
    df.rename(columns={'maxwspd':'windspd','maxtemp':'tmax', 'mintemp':'tmin', 'min humidity':'prain'}, inplace= True)
    df = df[df['tmin']> 0]
    X = df[['tmin']]
    
#     X= df.where(['tmin'>0])
    col_names = list(X.columns)
#     sc_X = pickle.load(open('sc_X2.pkl','rb'))
#     sc_Y = pickle.load(open('sc_Y2.pkl','rb'))
    X_df= sc_X.fit_transform(X)
    X_df = pd.DataFrame(X_df, columns=col_names)
    y = model.predict(X_df)
    realfeelmin = sc_Y.inverse_transform(y)
    df['realfeelmin']=realfeelmin + 0.75
    df.to_csv(file)
#     X_df.describe().T


In [39]:
df['newyear'] = pd.to_datetime('2019/01/01')
df['date']=pd.to_datetime(df['date'])
df['days']=df['date'] - df['newyear']
df['days'] = df['days'].dt.days

df.rename(columns={'maxwspd':'windspd','maxtemp':'tmax', 'mintemp':'tmin'}, inplace= True)


In [40]:
X = df[['tmin']]

In [54]:
# X= X[['tmin']]
col_names = list(X.columns)
sc_X = pickle.load(open('sc_X.pkl','rb'))
sc_Y = pickle.load(open('sc_Y.pkl','rb'))
X_df= sc_X.fit_transform(X)
X_df = pd.DataFrame(X_df, columns=col_names)   
X_df.describe().T

count          mean       std       min       25%       50%       75%  \
tmin  153.0 -1.059429e-16  1.003284 -4.697061 -0.766925  0.089577  0.947365   

           max  
tmin  1.375616

In [55]:
model = keras.models.load_model('C://Users/Akash/New folder (4)/Untitled Folder/model')
model.load_weights('weights_realfeel.h5')

In [56]:
model.weights

[<tf.Variable 'dense_12/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[ 0.05401128,  2.3274045 ,  0.34550416, -1.4530439 ]],
       dtype=float32)>,
 <tf.Variable 'dense_12/bias:0' shape=(4,) dtype=float32, numpy=array([-1.6898173 , -3.1309562 , -0.12745638, -2.0728042 ], dtype=float32)>,
 <tf.Variable 'dense_13/kernel:0' shape=(4, 1) dtype=float32, numpy=
 array([[ 1.8287061],
        [ 2.2459507],
        [ 1.0845464],
        [-2.635155 ]], dtype=float32)>,
 <tf.Variable 'dense_13/bias:0' shape=(1,) dtype=float32, numpy=array([-0.6733416], dtype=float32)>]

In [57]:
y = model.predict(X_df)

In [58]:
y

array([[ 0.96821326],
       [ 0.5230331 ],
       [ 0.7764835 ],
       [ 1.0704677 ],
       [ 1.1733553 ],
       [ 1.0704677 ],
       [ 1.0704677 ],
       [ 1.384002  ],
       [ 0.8711521 ],
       [ 1.0704677 ],
       [ 1.0704677 ],
       [ 1.1733553 ],
       [ 0.96821326],
       [ 0.96821326],
       [ 0.96821326],
       [ 0.8711521 ],
       [ 0.5230331 ],
       [ 0.6030238 ],
       [ 0.7764835 ],
       [ 0.6880838 ],
       [ 0.7764835 ],
       [ 0.7764835 ],
       [ 1.0704677 ],
       [ 0.8711521 ],
       [ 0.7764835 ],
       [ 0.8711521 ],
       [-2.8963516 ],
       [ 1.0704677 ],
       [ 0.96821326],
       [ 0.96821326],
       [ 1.1733553 ],
       [ 0.96821326],
       [ 0.96821326],
       [ 1.0704677 ],
       [ 0.7764835 ],
       [ 0.5230331 ],
       [ 0.8711521 ],
       [ 1.0704677 ],
       [ 1.0704677 ],
       [ 1.0704677 ],
       [ 1.0704677 ],
       [ 1.1733553 ],
       [ 1.0704677 ],
       [ 0.96821326],
       [ 0.96821326],
       [ 0

In [59]:
realfeelmin = sc_X.inverse_transform(y)

In [60]:
df['realfeelmin']=realfeelmin

In [61]:
df.to_csv('C://Users/Akash/New folder (4)/Untitled Folder/north/ludhiana-2019.csv')

In [62]:
realfeelmin

array([[26.27211  ],
       [22.81047  ],
       [24.781254 ],
       [27.06722  ],
       [27.867256 ],
       [27.06722  ],
       [27.06722  ],
       [29.505203 ],
       [25.51738  ],
       [27.06722  ],
       [27.06722  ],
       [27.867256 ],
       [26.27211  ],
       [26.27211  ],
       [26.27211  ],
       [25.51738  ],
       [22.81047  ],
       [23.432465 ],
       [24.781254 ],
       [24.093876 ],
       [24.781254 ],
       [24.781254 ],
       [27.06722  ],
       [25.51738  ],
       [24.781254 ],
       [25.51738  ],
       [-3.7780223],
       [27.06722  ],
       [26.27211  ],
       [26.27211  ],
       [27.867256 ],
       [26.27211  ],
       [26.27211  ],
       [27.06722  ],
       [24.781254 ],
       [22.81047  ],
       [25.51738  ],
       [27.06722  ],
       [27.06722  ],
       [27.06722  ],
       [27.06722  ],
       [27.867256 ],
       [27.06722  ],
       [26.27211  ],
       [26.27211  ],
       [24.781254 ],
       [26.27211  ],
       [24.78

In [63]:
X_df

tmin
0    1.090116
1    0.732597
2    0.947365
3    1.162134
4    1.232866
..        ...
148 -1.695445
149 -1.695445
150 -1.767463
151 -1.767463
152 -1.839482

[153 rows x 1 columns]

In [94]:
X

0       True
1       True
2       True
3       True
4       True
       ...  
148    False
149    False
150    False
151    False
152    False
Name: tmin, Length: 153, dtype: bool

In [99]:
df[df['tmin']>20]

Unnamed: 0       date   tmax  avgtemp   tmin  maxdewpt  avgdewpt  \
0            1 2020-08-01  32.78    28.89  27.22        81      78.4   
1            2 2020-08-02  37.22    32.17  26.11        79      75.8   
2            3 2020-08-03  31.11    27.17  22.78        81      76.0   
3            4 2020-08-04  36.11    32.44  27.78        81      78.0   
4            5 2020-08-05  33.89    29.83  26.11        81      78.6   
..         ...        ...    ...      ...    ...       ...       ...   
82          85 2020-10-22  33.89    28.94  22.78        59      50.7   
83          86 2020-10-23  33.89    28.33  22.78        52      46.6   
84          87 2020-10-24  33.89    27.44  22.22        48      40.0   
85          88 2020-10-25  33.89    27.06  21.11        50      43.8   
86          89 2020-10-26  32.78    27.17  21.11        50      41.7   

    mindewpt  max humidity  avg humidity  min humidity  windspd  avgwspd  \
0         77            94          83.0            63        6      1.4   
1         70            89          64.4            47       10      3.1   
2         73           100          85.7            70        9      2.9   
3         75            94          67.6            50        3      1.4   
4         75            89          78.8            67       17      4.3   
..       ...           ...           ...           ...      ...      ...   
82        45            53          32.3            22        3      2.0   
83        39            38          28.9            16        5      1.9   
84        32            41          24.1            11        5      1.8   
85        37            49          28.5            15        3      1.8   
86        34            49          26.3            15        6      2.0   

    minwspd  pressure  precipitation    newyear  days  
0         0      28.3            0.0 2020-01-01   213  
1         0      28.2            0.0 2020-01-01   214  
2         0      28.2            0.0 2020-01-01   215  
3         0      28.1            0.0 2020-01-01   216  
4         0      28.1            0.0 2020-01-01   217  
..      ...       ...            ...        ...   ...  
82        0      28.4            0.0 2020-01-01   295  
83        0      28.4            0.0 2020-01-01   296  
84        0      28.5            0.0 2020-01-01   297  
85        0      28.5            0.0 2020-01-01   298  
86        0      28.6            0.0 2020-01-01   299  

[82 rows x 18 columns]

In [103]:
df['tmin']=df['tmin']+0.75

In [ ]:
df